#! /usr/bin/env python
# -*- coding: utf-8 -*-
import os


if __name__ == '__main__':
    os.environ.setdefault("FAP_SETTINGS_MODULE", "$root_app$.settings")
    from faplus.management import execute_from_command_line
    execute_from_command_line()
